# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aff94f041814d00b099bb451986c3b7444966819b272cb86f8cf3c7fc15f7a778df5098ff9e728b2398f37e93d89b9608bb13e24ac69e3a974a561ef32471dd

test:
  secret_key_base: 762a68575e1e325d8774574c15a81400373c16432484e8378ba1030011d5567eba51b035580c0c784f9a6930805d8be195539f6e15919c06d829586e7cfafd6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
